#!/bin/bash

#
# Simple timeboxing tool
#

boxfile="$HOME/.boxfile"

if [ $# -eq 0 ] || [ "$1" = "-a" ]; then
    today=$( date +%m%d )
    if [ "$1" = "-a" ]; then
        readarray boxes < <( tail -n +1 $boxfile | sort )
    else
        readarray boxes < <( grep "$today" $boxfile )
    fi
    i=0
    while [ "$i" -lt $(( ${#boxes[@]} - 1 )) ]; do
        boxes[i]=$( echo ${boxes[i]} | tr -d "\n" )
        i=$(( i + 1 ))
    done
    echo
    select box in "${boxes[@]}"; do
        if [ -z "$box" ]; then
            echo "Invalid selection."
        else
            words=( $box )
            boxdate=${words[0]}
            minutes=${words[1]}
            seconds=${words[2]}
            description=$( echo $box | cut -d " " -f 4- | tr -d "\n" ) 
            echo
            echo "[Shift+P to pause.]"
            echo
            while true; do
                printf "%s: %3d:%02d\r" "$description" "$minutes" "$seconds"
                if [ "$minutes" -eq 0 ] && [ "$seconds" -eq 0 ]; then
                    echo
                    echo "You're done!"
                    echo "$( sed "/$box/d" $boxfile )" > $boxfile
                    break
                fi
                read -s -n 1 -t 1 input
                if [ "$input" = "P" ]; then
                    echo; echo
                    echo "Time remaining: $minutes min, $seconds seconds."
                    echo "$( sed "/$( echo $box | tr -d "\n" )/d" $boxfile )" > $boxfile
                    echo "$boxdate $minutes $seconds $description" >> $boxfile
                    break
                elif [ ! -z "$input" ]; then
                    echo; echo
                    echo "Invalid input: $input. Shift+P to pause."
                    echo
                    sleep 1
                fi
                seconds=$(( $seconds - 1 ))
                if [ "$seconds" -lt 0 ]; then
                    minutes=$(( $minutes - 1 ))
                    seconds=59
                fi
            done
            break
        fi
    done
elif [ "$1" = "-l" ]; then
    tail -n +1 $boxfile | sort
else
    echo "$@" >> $boxfile
    echo "Boxed."
fi
