#!/bin/bash

# To make the "moar!!" thing work just like for "wiki" and "moarwiki",
# add "alias moarcap=moarwiki" to your .bashrc. (Then enter "source ~/.bashrc"
# into your terminal, lest you must wait til the next reboot.)

echo -n "Captain here! "; wiki $@ | tail -n +2 | head -c -2; echo " *Flies away*"
