#!/bin/bash

while true; do
    for i in $( seq 4 ); do
        echo "Start work"
        mpc toggle
        if [ $i -lt 4 ]; then
            sleep 25m && mpc toggle && echo "Short break" && sleep 5m
        else
            sleep 25m && mpc toggle && echo "Long break" && sleep 15m
        fi
    done
done
