#!/bin/bash

if [ $# = 0 ]; then
    MESSAGE="Go do the thing."
else
    MESSAGE="$@"
fi

ADMONITION=

while true; do
    for i in $( ls ~/Pictures/ascii | sort -R ); do
        if [ -z "$ADMONITION" ] || [ "$ADMONITION" = "No srsly." ]; then
            ADMONITION=" $MESSAGE"
        elif [ ${#ADMONITION} -gt 10000000 ]; then
            ADMONITION="No srsly."
        else
            ADMONITION="  $ADMONITION  $ADMONITION "
        fi
        echo "$ADMONITION"
        sleep 1
        cat ~/Pictures/ascii/$i
        sleep 1
    done
done
