#!/bin/bash

function help {
    echo "Usage: timer NUMBER[SUFFIX]..."
    echo
    echo "where NUMBER[SUFFIX]... determines the time until"
    echo "the timer goes off. The formatting is inherited"
    echo "from the \"sleep\" command. \"sleep --help\" and"
    echo "\"man sleep\" are your friends."
    echo
    echo "Nontrivial dependencies:"
    echo "      slideshow [local], bspwm, mpd, mpc, urxvt"
}

function error {
    help
    exit 1
}

if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    help
    exit 0
fi

if [ "$1" = "-m" ]; then
    MESSAGE="$2"
    shift
    shift
else
    MESSAGE=
fi

(
    sleep $@ 2>/dev/null || error
    mpc -q toggle
    urxvt -hold -e bash -c "bspc window -t fullscreen && slideshow $MESSAGE" &&
    echo "Have you done the thing?"
) &

RELATIVE_TIME=$( echo $@ | sed 's/h/\ hour/;s/m/\ min/;s/s/\ sec/' )
ABSOLUTE_TIME=$( date -d "$RELATIVE_TIME" )

echo "Timer set for $ABSOLUTE_TIME."
